name: "CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-root-flake:
    name: "Zero-Dependency Check"
    runs-on: ubuntu-24.04
    permissions:
      contents: "read"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Verify Root Flake Schema & Zero Dependencies
        run: nix flake check --show-trace

  run-unit-tests:
    name: "nix-unit Test Suite & NixOS Matrix"
    runs-on: ubuntu-24.04
    needs: check-root-flake
    permissions:
      contents: "read"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false

      - name: Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - name: Run Flake Unit & Integration Checks
        run: nix flake check ./tests --show-trace
